# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 993434615bfedbb5031ec00a70156fe63b74b401c2b367d76b2d67fb6d4a4bc014ca6229fcb44da5c401ee992553c9987effd1edaee28d419ad442df17853ab6

test:
  secret_key_base: 98850e8a8978ae83864f66cbbefe2d4502cc1218e7db065799adb7831efdc6ed2bc14f00e5dbea1503f483b5efb6d9acba84b06b5676909ea645c81b4e888b13

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
